@Mimir.Server_HostAddress = https://localhost:7356
@Server_HostAddress = http://localhost:5504

GET {{Server_HostAddress}}/api/weatherforecast/
Accept: application/json

GET {{Server_HostAddress}}/api/mimirpostgres/
Accept: application/json



###
@userAndPass=testtest
POST {{Mimir.Server_HostAddress}}/api/mimirpostgres?userAndPass={{userAndPass}}

###

@uidAndToken=12:D36HGWeraRZVzaWfsAQDbP6ONTLh3YqIH
POST {{Mimir.Server_HostAddress}}/api/mimirpostgresgetuseraccount?uidAndToken={{uidAndToken}}

###
